up:
	sudo docker compose up --remove-orphans -d

down:
	sudo docker compose down

logs:
	sudo docker compose logs -f

update:
	sudo docker compose pull
	sudo docker compose up --remove-orphans -d --force-recreate